name: Generate 3D Contribution Graph

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
